# Generated by Django 2.0.1 on 2018-01-27 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180127_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='path',
            new_name='name',
        ),
    ]
