# Generated by Django 2.0.1 on 2018-01-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_photo_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='n_comments',
            field=models.IntegerField(default=0),
        ),
    ]
