# Generated by Django 2.0.1 on 2018-01-27 18:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_photo_n_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='n_comments',
            new_name='commentsCount',
        ),
        migrations.AddField(
            model_name='profile',
            name='photosCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
