# Generated by Django 2.0.1 on 2018-01-28 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
